Fixed AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next' based on https://stackoverflow.com/questions/74289077/attributeerror-multiprocessingdataloaderiter-object-has-no-attribute-next I too faced the same issue, when i tried to call the next() method as follows
dataiter = iter(dataloader)
data = dataiter.next()
You need to use the following instead and it works perfectly:

dataiter = iter(dataloader)
data = next(dataiter)